### ISSUE TITLE
The plugin has not been working properly on Chrome for some time.

### ISSUE THREAD

**Issue by Gopher0727** [sa-paul/FetchCode#3]
![image](https://github.com/user-attachments/assets/fcfac371-1525-4956-8951-8505462a1202)
It displays "No result found". It may be related to the interface provided by Chrome, which can run normally in the Edge browser.

**Comment by Gopher0727** [comment]
Chrome version: 128.0.6613.85
plugin version: 0.1.1
Operation System: win11 23H2 22631.4037

**Comment by sa-paul** [comment]
@Tsignorino 

Can you please provide:

* A link to the problem you are referring to
* A detailed description of the issue you are encountering, including the timing (e.g., during CodeForces contest or other)
* Clarification on "some time": does the "No Result Found" error occur intermittently with results available after a delay (e.g., 1-2 minutes), or is the error constant for some problems with no results ever found?

### Please provide this information to help us better understand and address your issue.

**Comment by sayanpaulcse** [comment]
@Tsignorino 

Can you please provide:

* A link to the problem you are referring to
* A detailed description of the issue you are encountering, including the timing (e.g., during CodeForces contest or other)
* Clarification on "some time": does the "No Result Found" error occur intermittently with results available after a delay (e.g., 1-2 minutes), or is the error constant for some problems with no results ever found?

### Please provide this information to help us better understand and address your issue.

**Comment by Tsignorino** [comment]
Sorry, my issue is really crude. 

I mean, it seems that this plug-in doesn't work properly. In the past, I was able to click on the title page provided to view the code of my friends, but now it has been a week or two since there is no result on the Chrome browser. 

Chrome browser update and plug-in reinstallation can't solve the problem.

As for the link, I can't get the submission for any topic that friends did on the codeforces topic page.

After investigation, I don't think it's not because of my computer. The plug-in can be used normally on the edge browser. So I think there may be some problems with the Chrome interface.

**Comment by Gopher0727** [comment]
Sorry, my issue is really crude. 

I mean, it seems that this plug-in doesn't work properly. In the past, I was able to click on the title page provided to view the code of my friends, but now it has been a week or two since there is no result on the Chrome browser. 

Chrome browser update and plug-in reinstallation can't solve the problem.

As for the link, I can't get the submission for any topic that friends did on the codeforces topic page.
eg：https://codeforces.com/contest/622/problem/C

After investigation, I don't think it's because of my computer. The plug-in can be used normally on the edge browser. So I think there may be some problems with the Chrome interface.
